- name: Executing remote SSH commands to deploy
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: ${{ secrets.SSH_PORT }}
    script: |
      set -e

      cd /var/www/devops-fastapi-assignment

      echo "Pull latest code..."
      git pull origin main

      echo "Stopping old containers..."
      docker compose down --remove-orphans

      echo "Building and starting containers..."
      docker compose up -d --build

      echo "Waiting for application..."
      sleep 20

      echo "Checking Health..."
      STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/health)

      if [ "$STATUS" = "200" ]; then
          echo "Deployment Successful"
      else
          echo "Deployment Failed"
          exit 1
      fi

      docker compose ps